name: Link Checker

on: [push, pull_request]

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Lychee broken link checker
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: ./ --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
